xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_01_San Andreas Fault.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_02_Wonder.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_03_Beloved Wife.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_04_River.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_05_Carnival.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_06_I May Know the Word.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_07_The Letter.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_08_Cowboy Romance.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_09_Jealousy.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_10_Where I Go.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Natalie Merchant\01-Natalie Merchant_11_Seven Years.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Natalie Merchant\"
xcopy /yi "C:\MediaTracker\Music\MP3s\toriamos\01-Pretty Good Year.mp3" "C:\MediaTracker\ToBurn\MellowVol1\toriamos\"
xcopy /yi "C:\MediaTracker\Music\MP3s\toriamos\08-Cornflake Girl.mp3" "C:\MediaTracker\ToBurn\MellowVol1\toriamos\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_01_Sugar on My Tongue.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_02_I Want to Live.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_03_Love --- Building on Fire.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_04_I Wish You Wouldn't Say That.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_05_Psycho Killer.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_06_Don't Worry About the Government.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_07_No Compassion.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_08_Warning Sign.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_09_The Big Country.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_10_Take Me to the River.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_11_Heaven.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_12_Memories Can't Wait.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_13_I Zimbra.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_14_Once in a Lifetime.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_15_Crosseyed and Painless.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_16_Burning Down the House.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_17_Swamp.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\30-Talking Heads_18_This Must Be the Place (Naive Melody).mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_01_Life During Wartime [Live].mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_02_Girlfriend Is Better [Live].mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_03_And She Was.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_04_Stay up Late.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_05_Road to Nowhere.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_06_Wild Wild Life.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_07_Love for Sale.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_08_City of Dreams.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_09_Mr. Jones.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_10_Blind.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_11_(Nothing But) Flowers.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_12_Sax and Violins.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_13_Gangster of Love.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_14_Lifetime Piling Up.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Talking Heads\31-Talking Heads_15_Popsicle.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Talking Heads\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_01_FM.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_02_Black Friday.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_03_Babylon Sisters.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_04_Deacon Blues.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_05_Bodhisattva.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_06_Hey Nineteen.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_07_Do It Again.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_08_Peg.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_09_Rikki Don't Lose That Number.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_10_Reeling in the Years.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_12_Kid Charlemagne.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Steely Dan\Steely Dan_13_My Old School.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Steely Dan\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_01_Jimmy Durante - As Time Goes By.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_02_Louis Armstrong - A Kiss to Build a Dream On.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_03_Nat King Cole - Stardust.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_04_Dr. John - Makin' Whoopee (feat. Rickie Lee Jones).mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_05_Carly Simon - In the Wee Small Hours of the Morning.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_06_Gene Autry - Back in the Saddle Again.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_07_Joe Cocker - Bye Bye Blackbird.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_08_Harry Connick, Jr. - A Wink and a Smile.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_09_Tammy Wynette - Stand By Your Man.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_10_Harry Warren - An Affair to Remember .mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_11_Jimmy Durante - Make Someone Happy.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\SleeplessSeattleSoundtrack\Various_12_Celine Dion & Clive Griffin - When I Fall in Love.mp3" "C:\MediaTracker\ToBurn\MellowVol1\SleeplessSeattleSoundtrack\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Sinéad O'Connor\Sinead O'Connor_04_The Emperor's New Clothes.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Sinéad O'Connor\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Sinéad O'Connor\Sinead O'Connor_06_Nothing Compares 2 U.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Sinéad O'Connor\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\01_Simon & Garfunkel_Mrs. Robinson.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\02_Simon & Garfunkel_Homeward Bound.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\03_Simon & Garfunkel_America.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\04_Simon & Garfunkel_Me and Julio Down by the Schoolyard.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\05_Simon & Garfunkel_Scarborough Fair.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\06_Simon & Garfunkel_April Come She Will.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\07_Simon & Garfunkel_Wake Up Little Susie.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\08_Simon & Garfunkel_Still Crazy After All These Years.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\09_Simon & Garfunkel_American Tune.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\10_Simon & Garfunkel_Late in the Evening.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\11_Simon & Garfunkel_Slip Slidin' Away.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\12_Simon & Garfunkel_A Heart in New York.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\13_Simon & Garfunkel_Kodachrome-Maybellene.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\14_Simon & Garfunkel_Bridge over Troubled Water.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\15_Simon & Garfunkel_50 Ways to Leave Your Lover.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\16_Simon & Garfunkel_The Boxer.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\17_Simon & Garfunkel_Old Friends.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\18_Simon & Garfunkel_The 59th Street Bridge Song (Feelin' Groovy).mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Simon & Garfunkel\19_Simon & Garfunkel_The Sound of Silence.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Simon & Garfunkel\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Roxy Music\Roxy Music_01_More Than This.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Roxy Music\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Roxy Music\Roxy Music_03_Avalon.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Roxy Music\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\01-Steady, As She Goes.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\02-Hands.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\03-Broken Boy Soldier.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\04-Intimate Secretary.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\05-Together.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\06-Level.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\07-Store Bought Bones.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\08-Yellow Sun.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\09-Call It A Day.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Raconteurs\10-Blue Veins.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Raconteurs\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_01_The Boy in the Bubble.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_02_Graceland.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_03_I Know What I Know.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_04_Gumboots.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_05_Diamonds on the Soles of Her Shoes.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_06_You Can Call Me Al.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_07_Under African Skies.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_08_Homeless.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_09_Crazy Love, Vol. II.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_10_That Was Your Mother.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Paul Simon\Paul Simon_11_All Around the World or the Myth of Fingerprints.mp3" "C:\MediaTracker\ToBurn\MellowVol1\Paul Simon\"
