xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_01_Baba O'Riley.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\" 2> "C:\MediaTracker\ToBurn\BritishRockVol1\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_02_Bargain.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_03_Love Ain't for Keeping.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_04_My Wife.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_05_The Song Is Over.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_06_Getting in Tune.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_07_Going Mobile.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_08_Behind Blue Eyes.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\06-Who_09_Won't Get Fooled Again.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-01_The Who_I Am the Sea.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-02_The Who_The Real Me.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-03_The Who_Quadrophenia.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-04_The Who_Cut My Hair.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-05_The Who_The Punk and the Godfather.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-06_The Who_I'm One.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-07_The Who_The Dirty Jobs.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-08_The Who_Helpless Dancer.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-09_The Who_Is It in My Head-.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\07-10_The Who_I've Had Enough.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\08-01_The Who_5-15.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\08-02_The Who_Sea and Sand.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\08-03_The Who_Drowned.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\08-04_The Who_Bell Boy.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\08-05_The Who_Doctor Jimmy.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\08-06_The Who_The Rock.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\08-07_The Who_Love, Reign O'er Me.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_01_You Better You Bet.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_02_Don't Let Go the Coat.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_03_Cache Cache.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_04_The Quiet One.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_05_Did You Steal My Money.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_06_How Can You Do It Alone.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_07_Daily Records.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_08_You.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_09_Another Tricky Day.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_10_I Like Nightmares [#][-].mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_11_It's in You [#][-].mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_12_Somebody Saved Me [#][-].mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_13_How Can You Do It Alone [#][-][Live].mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\13-The Who_14_The Quiet One [#][-][Live].mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\17 - Eminence Front.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Who\24 - Were Not Gonna Take It (Original Album Edit).mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\Who\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-01-Good Times Bad Times.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-02-Babe I'm Gonna Leave You.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-03-You Shook Me.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-04-Dazed and Confused.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-05-Your Time Is Gonna Come.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-06-Black Mountain Side.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-07-Communication Breakdown.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-08-I Can't Quit You Baby.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\1-09-How Many More Times.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_01_Black Dog.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_02_Rock and Roll.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_03_The Battle of Evermore.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_04_Stairway to Heaven.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_05_Misty Mountain Hop.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_06_Four Sticks.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_07_Going to California.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\4-Led Zeppelin_08_When the Levee Breaks.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_01_The Song Remains the Same.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_02_The Rain Song.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_03_Over the Hills and Far Away.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_04_The Crunge.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_05_Dancing Days.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_06_D'Yer Mak'er.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_07_No Quarter.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\5-Led Zeppelin_08_The Ocean.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\6-Led Zeppelin_01_Custard Pie.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\6-Led Zeppelin_02_The Rover.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\6-Led Zeppelin_03_In My Time of Dying.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\6-Led Zeppelin_04_Houses of the Holy.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\6-Led Zeppelin_05_Trampled Under Foot.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\6-Led Zeppelin_06_Kashmir.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\7-Led Zeppelin_04_Ten Years Gone.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\7-Led Zeppelin_05_Night Flight.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\7-Led Zeppelin_06_The Wanton Song.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\7-Led Zeppelin_07_Boogie with Stu.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\7-Led Zeppelin_08_Black Country Woman.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\7-Led Zeppelin_09_Sick Again.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\8-Led Zeppelin_01_In the Evening.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\8-Led Zeppelin_02_South Bound Saurez.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\8-Led Zeppelin_03_Fool in the Rain.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\8-Led Zeppelin_04_Hot Dog.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\8-Led Zeppelin_05_Carouselambra.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\LedZeppelin\8-Led Zeppelin_06_All My Love.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\LedZeppelin\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_02_Instant Karma!.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_04_Whatever Gets You Thru the Night.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_05_#9 Dream.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_06_Mind Games.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_08_Happy Xmas (War Is Over).mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_09_Imagine.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_12_(Just Like) Starting Over.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_13_Woman.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_14_I'm Losing You.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_15_Beautiful Boy (Darling Boy).mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\John Lennon_16_Watching the Wheels.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
xcopy /yi "C:\MediaTracker\Music\MP3s\John Lennon\1984-081 John Lennon - Nobody Told Me.mp3" "C:\MediaTracker\ToBurn\BritishRockVol1\John Lennon\"
