xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_01_Highway to Hell.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_02_Girls Got Rhythm.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_03_Walk All over You.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_04_Touch Too Much.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_05_Beating Around the Bush.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_06_Shot Down in Flames.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_07_Get It Hot.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_08_If You Want Blood (You've Got It).mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\09-AC-DC_09_Love Hungry Man.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_02_Shoot to Thrill.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_03_What Do You Do for Money Honey.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_04_Givin the Dog a Bone.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_05_Let Me Put My Love into You.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_06_Back in Black.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_07_You Shook Me All Night Long.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_08_Have a Drink on Me.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_09_Shake a Leg.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\AC-DC\10-AC-DC_10_Rock and Roll Ain't Noise Pollution.mp3" "C:\MediaTracker\ToBurn\MetalVol2\AC-DC\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_01_In the Meantime.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_02_Ironhead.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_03_Give It.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_04_Unsung.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_05_Turned Out.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_06_He Feels Bad.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_07_Better.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_08_You Borrowed.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_09_FBLA II.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Helmet\02-Helmet_10_Role Model.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_01_Where Eagles Dare.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_02_Revelations.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_03_Flight of Icarus.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_04_Die With Your Boots On.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_05_The Trooper.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_06_Still Life.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_07_Quest for Fire.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_08_Sun and Steel.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_09_To Tame a Land.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\08-01_Judas Priest_Rapid Fire.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\08-02_Judas Priest_Metal Gods.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\08-03_Judas Priest_Breaking the Law.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\08-06_Judas Priest_You Don't Have to Be Old to Be Wise.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\08-07_Judas Priest_Living After Midnight.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\08-08_Judas Priest_The Rage.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\08-11_Judas Priest_Grinder [-][Live].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-01_Judas Priest_Heading Out to the Highway.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-02_Judas Priest_Don't Go.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-03_Judas Priest_Hot Rockin'.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-04_Judas Priest_Turning Circles.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-05_Judas Priest_Desert Plains.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-06_Judas Priest_Solar Angels.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-07_Judas Priest_You Say Yes.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-08_Judas Priest_All the Way.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-09_Judas Priest_Troubleshooter.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-10_Judas Priest_On the Run.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\09-12_Judas Priest_Desert Plains [-][Live].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_01_The Hellion.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_02_Electric Eye.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_03_Riding on the Wind.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_04_Bloodstone.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_05_(Take These) Chains.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_06_Pain and Pleasure.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_07_Screaming for Vengeance.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_08_You've Got Another Thing Comin'.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_09_Fever.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\10-Judas Priest_10_Devil's Child.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-01_Judas Priest_Freewheel Burning.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-02_Judas Priest_Jawbreaker.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-03_Judas Priest_Rock Hard Ride Free.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-04_Judas Priest_The Sentinel.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-05_Judas Priest_Love Bites.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-06_Judas Priest_Eat Me Alive.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-07_Judas Priest_Some Heads Are Gonna Roll.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-08_Judas Priest_Night Comes Down.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-09_Judas Priest_Heavy Duty.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-10_Judas Priest_Defenders of the Faith.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\11-12_Judas Priest_Heavy Duty-Defenders of the Faith [-][Live].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\12-01_Judas Priest_Turbo Lover.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\12-04_Judas Priest_Parental Guidance.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\12-08_Judas Priest_Hot for Love.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\12-09_Judas Priest_Reckless.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\12-10_Judas Priest_All Fired Up [#][-].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\12-11_Judas Priest_Locked In [#][-][Live].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-01_Judas Priest_Exciter.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-02_Judas Priest_Running Wild.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-03_Judas Priest_Sinner.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-04_Judas Priest_The Ripper.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-05_Judas Priest_Green Manalishi (With the Two-Pronged Crown).mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-06_Judas Priest_Diamonds and Rust.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-07_Judas Priest_Victim of Changes.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-08_Judas Priest_Genocide.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-09_Judas Priest_Tyrant.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-11_Judas Priest_Delivering the Goods [-].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-12_Judas Priest_Hell Bent for Leather [-].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Judas Priest\35-13_Judas Priest_Starbreaker [-].mp3" "C:\MediaTracker\ToBurn\MetalVol2\Judas Priest\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\PerfectCircle\01-The Hollow.mp3" "C:\MediaTracker\ToBurn\MetalVol2\PerfectCircle\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\PerfectCircle\04-Judith.mp3" "C:\MediaTracker\ToBurn\MetalVol2\PerfectCircle\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\PerfectCircle\06-3 Libras.mp3" "C:\MediaTracker\ToBurn\MetalVol2\PerfectCircle\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\PerfectCircle\08-Thomas.mp3" "C:\MediaTracker\ToBurn\MetalVol2\PerfectCircle\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Rob Zombie\Rob Zombie_01_Call of the Zombie.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Rob Zombie\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Rob Zombie\Rob Zombie_02_Superbeast.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Rob Zombie\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Rob Zombie\Rob Zombie_03_Dragula.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Rob Zombie\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Rob Zombie\Rob Zombie_04_Living Dead Girl.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Rob Zombie\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_01_Scorpions_Blackout.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_02_Scorpions_Can't Live Without You.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_03_Scorpions_No One Like You.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_04_Scorpions_You Give Me All I Need.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_05_Scorpions_Now!.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_06_Scorpions_Dynamite.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_07_Scorpions_Arizona.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_08_Scorpions_China White.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\10_09_Scorpions_When the Smoke Is Going Down.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_01_Bad Boys Running Wild.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_02_Rock You Like a Hurricane.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_03_I'm Leaving You.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_04_Coming Home.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_05_The Same Thrill.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_06_Big City Nights.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_07_As Soon as the Good Times Roll.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_08_Crossfire.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "C:\MediaTracker\Music\MP3s\Scorpions\12-Scorpions_09_Still Loving You.mp3" "C:\MediaTracker\ToBurn\MetalVol2\Scorpions\" 2>> "C:\MediaTracker\ToBurn\MetalVol2\err.log"
