xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_01_Foreigner_Feels Like the First Time.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_03_Foreigner_Starrider.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_04_Foreigner_Headknocker.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_05_Foreigner_The Damage Is Done.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_06_Foreigner_Long, Long Way From Home.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_07_Foreigner_Woman Oh Woman.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_08_Foreigner_At War With the World.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_09_Foreigner_Fool for You Anyway.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Foreigner\01_10_Foreigner_I Need You.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Foreigner\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_01_In the Meantime.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_02_Ironhead.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_03_Give It.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_04_Unsung.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_05_Turned Out.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_06_He Feels Bad.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_07_Better.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_08_You Borrowed.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_09_FBLA II.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Helmet\02-Helmet_10_Role Model.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Helmet\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_01_Where Eagles Dare.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_02_Revelations.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_03_Flight of Icarus.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_04_Die With Your Boots On.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_05_The Trooper.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_06_Still Life.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_07_Quest for Fire.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_08_Sun and Steel.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Iron Maiden\Iron Maiden_09_To Tame a Land.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Iron Maiden\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\11 - Voodoo Child (Slight Return).mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_01_Hey Joe.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_02_Stone Free.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_03_Purple Haze.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_04_51st Anniversary.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_05_The Wind Cries Mary.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_06_Highway Chile.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_07_Foxey Lady.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_08_Manic Depression.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_12_I Don't Live Today.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_14_Fire.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_16_Remember.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\33_Jimi Hendrix Experience_17_Are You Experienced-.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_05_Jimi Hendrix_All Along the Watchtower.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_07_Jimi Hendrix_Crosstown Traffic.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_09_Jimi Hendrix_Little Wing.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_10_Jimi Hendrix_If 6 Was 9.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_12_Jimi Hendrix_Bold as Love.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_13_Jimi Hendrix_Castles Made of Sand.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_14_Jimi Hendrix_Red House.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_16_Jimi Hendrix_Freedom.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_17_Jimi Hendrix_Night Bird Flying.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_18_Jimi Hendrix_Angel.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_19_Jimi Hendrix_Dolly Dagger.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\JimiHendrixExperience\34_20_Jimi Hendrix_The Star Spangled Banner.mp3" "I:\MediaTracker\ToBurn\MetalVol2\JimiHendrixExperience\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-01_Judas Priest_Heading Out to the Highway.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-02_Judas Priest_Don't Go.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-03_Judas Priest_Hot Rockin'.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-04_Judas Priest_Turning Circles.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-05_Judas Priest_Desert Plains.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-06_Judas Priest_Solar Angels.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-07_Judas Priest_You Say Yes.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-08_Judas Priest_All the Way.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-09_Judas Priest_Troubleshooter.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-10_Judas Priest_On the Run.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\09-12_Judas Priest_Desert Plains [-][Live].mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_01_The Hellion.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_02_Electric Eye.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_03_Riding on the Wind.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_04_Bloodstone.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_05_(Take These) Chains.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_06_Pain and Pleasure.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_07_Screaming for Vengeance.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_08_You've Got Another Thing Comin'.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_09_Fever.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\10-Judas Priest_10_Devil's Child.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-01_Judas Priest_Freewheel Burning.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-02_Judas Priest_Jawbreaker.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-03_Judas Priest_Rock Hard Ride Free.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-04_Judas Priest_The Sentinel.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-05_Judas Priest_Love Bites.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-06_Judas Priest_Eat Me Alive.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-07_Judas Priest_Some Heads Are Gonna Roll.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-08_Judas Priest_Night Comes Down.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-09_Judas Priest_Heavy Duty.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-10_Judas Priest_Defenders of the Faith.mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\judas priest\11-12_Judas Priest_Heavy Duty-Defenders of the Faith [-][Live].mp3" "I:\MediaTracker\ToBurn\MetalVol2\judas priest\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_01_We Will Rock You.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_02_We Are the Champions.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_03_Another One Bites the Dust.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_04_Killer Queen.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_05_Somebody to Love.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_06_Fat Bottomed Girls.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_07_Bicycle Race.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_08_You're My Best Friend.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_09_Crazy Little Thing Called Love.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_10_Now I'm Here.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_11_Play the Game.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_12_Seven Seas of Rhye.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_13_Body Language.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_14_Save Me.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_15_Don't Stop Me Now.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_16_Good Old Fashioned Lover Boy.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
xcopy /yi "I:\MediaTracker\Music\MP3s\Queen\Queen_17_I Want to Break Free.mp3" "I:\MediaTracker\ToBurn\MetalVol2\Queen\" 2>> "I:\MediaTracker\ToBurn\MetalVol2\err.log"
