xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\01-Cranberries_01_I Still Do.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\01-Cranberries_02_Dreams.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\01-Cranberries_07_Linger.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_01_Ode to My Family.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_02_I Can't Be With You.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_03_Twenty-One.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_04_Zombie.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_09_Ridiculous Thoughts.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_10_Dreaming My Dreams.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_11_Yeat's Grave.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_12_Daffodil Lament.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\02-Cranberries_13_No Need to Argue.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\03-The Cranberries_01_Hollywood.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\03-The Cranberries_02_Salvation.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\03-The Cranberries_03_When You're Gone.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\03-The Cranberries_04_Free to Decide.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
xcopy /yi "C:\MediaTracker\Music\MP3s\Cranberries\03-The Cranberries_05_War Child.mp3" "C:\MediaTracker\ToBurn\AltOldiesVol1\Cranberries\"
